// <auto-generated />
using System;
using LogDeDados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogDeDados.Migrations
{
    [DbContext(typeof(LogDeDadosContext))]
    partial class LogDeDadosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogDeDados.Models.Log", b =>
                {
                    b.Property<int>("IDLog")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Etapa");

                    b.Property<string>("Evento");

                    b.Property<DateTime>("FIm");

                    b.Property<int>("IDUsuario");

                    b.Property<DateTime>("Inicio");

                    b.HasKey("IDLog");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("LogDeDados.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<Guid>("Token");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LogDeDados.Models.Log", b =>
                {
                    b.HasOne("LogDeDados.Models.Usuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
